import "./globals.css";
import { crimsonText, oxygen, dmSans, inter, oxygenMono } from "./fonts";
import '@rainbow-me/rainbowkit/styles.css';
import Providers from "./providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" 
      className={`${crimsonText.variable} ${oxygen.variable} ${dmSans.variable} ${inter.variable} ${oxygenMono.variable}`}
    >
      <body className={`bg-background`}>
       <Providers>
        {children}
       </Providers>
      </body>
    </html>
  );
}

